### ISSUE TITLE
WordPress Admin Bar

### ISSUE THREAD

**Issue by adamf321** [moxie-leean/ng-cms#14]
We need a way to replicate the WP admin bar. We will need to determine if a user is logged in and what capabilities they have in order to show the relevant options.

**Comment by adamf321** [comment]
Based on the standard bar (http://snaps.getmoxied.net/0u1R2g0l3J1U), we need to include the following features:
- Site name links to the dashboard ( admin_url() )
- New menu expands to show all the new cpt's they have permission to add (e.g. post, page, etc)
- Edit page links to the edit screen for the current page
- Logout option in the top right

**Comment by adamf321** [comment]
@andybar2 I wonder if we could do this by checking if the wp auth cookie exists? I'm not sure if you can tell if the user is logged in from the cookie (if not i guess we could generate a cookie when they do log in). This way we don't need to make an api call if they're not logged in.

If they become logged in whilst using the app (eg by logging in in another tab) - is there an easy way to detect the cookie has appeared and show the admin bar?

I was also thinking about the design of the bar - it might make it easier for styling if we made it partially transparent and position absolute at the top of the page, this way we could put it over the page content without adjusting it when the user is logged in. @nacho87 what do you think about this?

**Comment by mitogh** [comment]
This is working fine now. 

Can we close this @adamf321 or @andybar2 ?

Thanks.

**Comment by andybar2** [comment]
Yes, I think we can close it @mitogh .

**Comment by mitogh** [comment]
Thanks
