### ISSUE TITLE
Handle 404's

### ISSUE THREAD

**Issue by adamf321** [moxie-leean/ng-cms#4]
If a slug isn't found then we should use a default 404 template. This template can be overwritten for each project.

**Comment by andybar2** [comment]
Solved here: https://github.com/moxie-leean/ng-cms/commit/843daa6df61509e489016cf96b9ff7f61920cc81

I'll add the not-found route and template to the ng-web-app.

**Comment by adamf321** [comment]
@andybar2 can you open a PR please? (or 2 PR's, one for this repo and one for ng-web-app)

**Comment by andybar2** [comment]
PR for ng-cms: https://github.com/moxie-leean/ng-cms/pull/13
PR for ng-web-app: https://github.com/moxie-leean/ng-web-app/pull/43
