### ISSUE TITLE
Meta directive

### ISSUE THREAD

**Issue by adamf321** [moxie-leean/ng-cms#5]
Create a directive for meta data which will go in the `<head>` 

The data will be returned with the view's content.

**Comment by andybar2** [comment]
Solved here: https://github.com/moxie-leean/ng-cms/commit/b85646d24826e2c8f337a338618c3fd265d88784

The only way I found to make it work till now, is by nesting dynamic meta tags inside the meta tag used for the directive. E.g.:

``` html
<head>
  <meta ln-cms-head view-def="{{vm.view}}">
  ...
</head>
```

Will generate things like this:

``` html
<head>
  <meta ln-cms-head="" view-def="..." class="ng-isolate-scope">
    <title>My AngularJS App - Home</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </meta>
  ...
</head>
```

And it seems to work fine at least in chrome...

**Comment by adamf321** [comment]
@andybar2 I have a few comments... i should have given you better reqs, sorry!

The view will include the meta fields in json, something like this (this hasn't been implemented in the api yet, so you can change it you need to):

```
"meta": {
  "title": "...",
  "description": "...",
  "og": {
    "title": "...",
    ...
  },
  "twitter": {
    ...
 }
}
```

We need to output these og and twitter tags too: http://snaps.getmoxied.net/2Q1E28011Z31

I don't think the viewport tag needs to go here (that can be placed directly in the html as it won't change).

I'm not sure about the nested meta... it's not standard and it worries me that it might cause us issues with search engines. Could we do it by placing an attribute directive in the head and controlling the tags that way? `<head ln-cms-meta="{{view.meta}}" ... >`.

Can you open pull requests when you have code to merge?

**Comment by andybar2** [comment]
Ok, now it is working as requested.

The directive should be referenced from head tag, like this:

``` html
<head ln-cms-meta="{{vm.view.meta}}">
```

And the api should return metadata for each view in the following format:

``` javascript
"meta": {
  "title": "My AngularJS App - Home",
  "tags": [
    {"name": "description", "content": ""},
    {"property": "og:locale", "content": "en_US"},
    {"name": "twitter:card", "content": "summary"},
    ...
  ]
}
```

PR: https://github.com/moxie-leean/ng-cms/pull/13
